### ISSUE TITLE
Upgrade the CSS framework

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris-synoptic#46]

**Comment by ad0v0** [comment]
Hi! @aptiko Please review this pull request when you get a chance: https://github.com/openmeteo/enhydris-synoptic/pull/49/

**Comment by ad0v0** [comment]
@aptiko Hi! I'm facing some problems with pushing to remote branch. Please take a look at this message when  you get a chance: https://github.com/openmeteo/enhydris-synoptic/pull/49#issuecomment-698940011

**Comment by ad0v0** [comment]
@aptiko The feedback is implemented.

**Comment by ad0v0** [comment]
@aptiko Hi! Please take a look at my questions when you get a chance:
First: https://github.com/openmeteo/enhydris-synoptic/pull/49#issuecomment-705594359
Second: https://github.com/openmeteo/enhydris-synoptic/pull/49#issuecomment-705634435
